version: "3"

services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      VWORLD_API_KEY: ${VWORLD_API_KEY}
      DATA_ROOT: ${DATA_ROOT}
    volumes:
      - ./data:/app/data